apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: osd-metrics-exporter
  annotations:
    name: annotation
spec:
  scopes:
  - Cluster
  phases:
  - name: crds
  - name: cleanup-rbac
  - name: cleanup-deploy
  - name: rbac
  - name: deploy
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: 'True'
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  config:
    openAPIV3Schema:
      type: object
      properties:
        image:
          description: Operator image to deploy
          type: string
          default: None
test:
  template:
  - name: default
    context:
      package:
        metadata:
          name: osd-metrics-exporter
          namespace: openshift-osd-metrics
      config:
        image: "quay.io/example/osd-metrics-exporter:test"