# Allow watching and reading configmaps in openshift config. 
# 
# This file is deployed using a hive syncset. When making changes to this file,
# make sure to also update ../hack/olm-registry/olm-artifacts-template.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-metrics-exporter-watch-configmaps
  namespace: openshift-config
subjects:
  - kind: ServiceAccount
    name: osd-metrics-exporter
    namespace: openshift-osd-metrics
roleRef:
  kind: Role
  name: osd-metrics-exporter-watch-configmaps
  namespace: openshift-config
  apiGroup: rbac.authorization.k8s.io
